### ISSUE TITLE
Cannot compile the library with Arduino Nano

### ISSUE THREAD

**Issue by andrea1984** [melopero/Melopero_VL53L1X_Arduino_Library#1]
Because of the space required from the library, it cannot be used on Arduino Nano board.
This is the arduino error:

data section exceeds available space in board

Sketch uses 24850 bytes (80%) of program storage space. Maximum is 30720 bytes.
Global variables use 2829 bytes (138%) of dynamic memory, leaving -781 bytes for local variables. Maximum is 2048 bytes.
Not enough memory; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing your footprint.
Error compiling for board Arduino Nano.

**Comment by andrea1984** [comment]
I know that it's written on the README, but this library is not useful at all if it is not comaptible with Arduino Nano and One

**Comment by melopero** [comment]
Hi,

Thanks for pointing that out.
We decided to develop this library using the official ST Microelectronics API to offer the user the full set of features expected for the VL53L1X sensor. Unfortunately the full API is too big for some boards.
